name: Deploy master branch

on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: '10.x'
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.16.5'
      - name: Generate Prisma Client
        run: go run github.com/prisma/prisma-client-go generate
      - name: Run build
        run: env GOARCH=amd64 GOOS=linux go build -ldflags="-s -w" -o bin/server
      - name: Install Serverless Framework
        run: npm install -g serverless
      - name: Serverless AWS authentication
        run: sls config credentials --provider aws --key ${{ secrets.AWS_KEY }} --secret ${{ secrets.AWS_SECRET }}
      - name: Deploy Lambda functions
        run: sls deploy --verbose